### ISSUE TITLE
Could you please add some examples?

### ISSUE THREAD

**Issue by guoxj** [happykevins/cocos2dx-ext#1]
hi, i have used your htmllabel,
could you please add some examples?

the code as belows:
    CCSize winsize = CCDirector::sharedDirector()->getWinSize();
    CCHTMLLabel\* pLabel2 = CCHTMLLabel::createWithString("<font color=\"#FF0000\">TestHTMLLabel</font>", CCSize(200,200),DFONT_DEFAULT_FONTALIAS);
    pLabel2->setAnchorPoint(ccp(0,0));
    pLabel2->setPosition( ccp(winsize.width / 2, winsize.height / 3) );
    this->addChild(pLabel2);

it doesn't show anything. 
could please figure it out?
thanks

**Comment by happykevins** [comment]
in progress ...
